version: '2'
services:
    configserver:
        container_name: config-server
        build:
            context: server
            dockerfile: Dockerfile
        # image: suhailn/config-server:latest
        environment: 
            GITHUB_URI: https://github.com/suhail-n/spring-cloud-config.git
            CONFIG_PATH: config-repo
        ports: 
            - 8888:8888
        networks:
        - spring-cloud-network
    configclient:
        container_name: config-client
        build: 
            context: client
            dockerfile: Dockerfile
        # image: suhailn/config-client:latest
        environment:
            URI: http://configserver:8888
            PROFILE: development
        ports:
            - 8080:8080
        networks:
        - spring-cloud-network
        depends_on:
            - configserver

networks:
    spring-cloud-network:
        driver: bridge